resources:
  repositories:
  - repository: self
  # Import the deploy framework.
  - repository: df
    type: git
    name: CVX-DevOps/PipelineFramework
    ref: refs/tags/3.1.0

stages:
- template: pipeline.yml@df
  parameters:
    project:
    - deploy_pool: 
        name: 'Default-Public'
        demands:
          - agent.os -equals Linux
      pipeline_pool: 
        name: 'Default-Public'
        demands:
          - agent.os -equals Linux
      name: deploy_vms
      type: ansible
      verbosity: -vvv
      force_install_roles: "requirements.yml"
      extra_ansible_vars: |
        cvx_az_client_id: "$(cvx_az_client_id)"
        cvx_az_client_secret: "$(cvx_az_client_secret)"
        azure_iaas_admin_password: "$(cvx_az_client_secret)"
        tenant_id: "$(tenant_id)"
        dc_subscription: 3fe02f66-a68a-4cc3-bf2e-625e5be45301
        dc_resource_group: "$(dc_resource_group)"
        cvx_secure_logging: false
        adauth_forest: "$(ad_auth_forest)" 
        adauth_password: "$(ad_auth_password)"
        adauth_dc:
          - "$(ad_auth_forest).chevron.net"
